name: flutter_note_app
description: A flutter application for taking notes.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  # Embedded, SQL database engine.
  sqflite: ^1.3.0
  # Provides common operations for manipulating paths: joining, splitting, normalizing, etc.
  path: any
  path_provider: any
  # Provides internationalization and localization facilities
  intl: ^0.16.0
  fleva_icons: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat/Caveat-Regular.ttf
        - asset: assets/fonts/Caveat/Caveat-Bold.ttf
          weight: 700
